### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by shanniruo-tytx** [hspark1212/MOFTransformer#118]
Can not connect https://figshare.com/ndownloader/files/40298992 which http response code is 403.
Does figshare have a mirror site,or if there is another way to get the data?
I tried to use an overseas proxy service, but still couldn't download it from figshare.

**Comment by paliwalpiyush151** [comment]
I am able to download **pmtransformer.ckpt** file after clicking the above link. There may be some network issue from you end. Please check. 

OR you can try this link : https://figshare.com/articles/dataset/PMTransformer_pre-trained_model/22698655/2
