### ISSUE TITLE
raw_{downstream}.json

### ISSUE THREAD

**Issue by gianmarco-terrones** [hspark1212/MOFTransformer#121]
In raw_{downstream}.json, what is the meaning of the float for each CIF name? For example, raw_example.json has entries that look like "msp+N624+E8": 1.0, 

Are these the "y" labels of the data?

**Comment by Yeonghun1675** [comment]
Hi @gianmarco-terrones,

You're right, the value that goes into the float is the target value (y) of the property you want to predict. For example, if downstream is "bandgap", the key in the JSON file would be the structure's name and the value would be bandgap.
