### ISSUE TITLE
Error with moftransformer.run

### ISSUE THREAD

**Issue by gianmarco-terrones** [hspark1212/MOFTransformer#123]
On my Mac, when I try to run moftransformer.run as described in https://hspark1212.github.io/MOFTransformer/getting_started/training.html, I get an error that I have included in the attached TXT file. Have you seen an error like this before?

example_train.py
```
import moftransformer
from moftransformer.examples import example_path

# data root and downstream from example
root_dataset = example_path['root_dataset']
downstream = example_path['downstream']
log_dir = './logs/'
# load_path = "pmtransformer" (default)

# kwargs (optional)
max_epochs = 10
batch_size = 8

moftransformer.run(root_dataset, downstream, log_dir=log_dir,                   
                   max_epochs=max_epochs, batch_size=batch_size,)
```

[terminal_output.txt](https://github.com/hspark1212/MOFTransformer/files/11620509/terminal_output.txt)

**Comment by hspark1212** [comment]
Thank you for your comment regarding the running issue on your Mac. 
Unfortunately, this repository is specifically designed to function optimally with pytorch and GPUs on Linux systems. 
Therefore, it would be great if you could explore the possibility of running it on a Linux system.

**Comment by gianmarco-terrones** [comment]
I see, thank you! I will try that out. It might be helpful to mention that the package is tested primarily for Linux systems in the README of the repo or in the documentation website.

**Comment by hspark1212** [comment]
Thank you for your feedback. We will make sure to update the README file and the docs to include a clear mention that this package is primarily tested for the Linux system.
When you have any trouble in running this package, please don't hesitate to let us know by creating an issue. Good luck !
