### ISSUE TITLE
Typo in Document (editable installation process)

### ISSUE THREAD

**Issue by MINGUUUS** [hspark1212/MOFTransformer#126]
Hello, world!

I have found a typo in the editable installation process.

$ git clone https://github.com/hspark1212/MOFTransformer.git
$ cd moftransformer
$ pip install -e .

After `git clone`, the name of folder is MOFTransformer. So I think the following is suitable.

 $ git clone https://github.com/hspark1212/MOFTransformer.git
$ cd MOFTransformer
$ pip install -e .

Thank you for your awesome work!

**Comment by hspark1212** [comment]
Hi, @MINGUUUS ! Thank you for your comment regarding typo. We will make sure to fix this typo from the upcoming 2.0.2 version.
