### ISSUE TITLE
tensorboard

### ISSUE THREAD

**Issue by gianmarco-terrones** [hspark1212/MOFTransformer#130]
After training a model (on a system with Red Hat Enterprise Linux Server version 7.9), I get this error when I try to use tensorboard as described [here](https://hspark1212.github.io/MOFTransformer/getting_started/training.html#example-for-training-pmtransformer-moftransformer):

```
(moftransformer_env) [gterrone@gibraltar-53 moftransformer]$  tensorboard --logdir=logs --bind_all
TensorFlow installation not found - running with reduced feature set.
/home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server)
/home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server)
/home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by /home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server)
/home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server)
/home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server)
/home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server)
/home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /home/gterrone/anaconda3/envs/moftransformer_env/lib/python3.9/site-packages/tensorboard_data_server/bin/server)
TensorBoard 2.13.0 at http://gibraltar-53.localdomain:6006/ (Press CTRL+C to quit)
```

**Comment by Yeonghun1675** [comment]
Hi @gianmarco-terrones,
Thank you for your interest in our MOFTransformer. 
We believe the issue is related to tensorboard installation. 
One guess is that there's an issue with installing gxx and gcc on anaconda during the griday installation process. 
Could you try testing without "griday installed" on a new virtual environment and let us know if it's still an issue!

As we've mentioned before, griday is being rewritten as python-based code. 
If this is indeed a griday issue, we'll work quickly to fix the code.

**Comment by gianmarco-terrones** [comment]
Hi @Yeonghun1675, I tried the command without installing GRIDAY and got the same error.

**Comment by hspark1212** [comment]
Hi @gianmarco-terrones,

We believe that the issue you are experiencing may be caused by compatibility between your Linux system and TensorBoard. Have you previously tested running TensorBoard on the Linux server?

**Comment by gianmarco-terrones** [comment]
I have not previously tested running TensorBoard on the Linux server (Red Hat Enterprise Linux Server version 7.9; Maipo), so that makes sense.

**Comment by hspark1212** [comment]
Please let us know if you encounter any issues when running TensorBoard with the MOFTranformer package while TensorBoard works well on the Linuz server !
