### ISSUE TITLE
Minor typo in documentation

### ISSUE THREAD

**Issue by gianmarco-terrones** [hspark1212/MOFTransformer#131]
https://hspark1212.github.io/MOFTransformer/getting_started/test.html#example-for-test-using-command-line
I believe "exmaple" should instead be "example"
`$ moftransformer run --root_dataset './data' --downstream 'exmaple' --test-only True --config load_path='path_load'`

**Comment by gianmarco-terrones** [comment]
Also, it appears that the code works as intended when I assess the test set using the [Python approach](https://hspark1212.github.io/MOFTransformer/getting_started/test.html#example-for-test-using-python), but when I use the [command-line approach](https://hspark1212.github.io/MOFTransformer/getting_started/test.html#example-for-test-using-python) I get the following error:

```
(moftransformer_env) [gterrone@gibraltar-53 moftransformer]$  moftransformer run --root_dataset './data' --downstream 'example' --test-only True --config load_path='path_load'
usage: moftransformer [-h] [--version] [-T] {help,install-griday,uninstall-griday,run,download} ...
moftransformer: error: unrecognized arguments: --root_dataset --downstream example --test-only True --config load_path=path_load
```

**Comment by Yeonghun1675** [comment]
Hi @gianmarco-terrones,
Thanks for pointing out the issue with our documentation! We'll fix it in the next version!
For the command-line, we've identified an issue with the code and are working on fixing it in the next version. Until then, please use python instead of the command line.
