### ISSUE TITLE
Baseline Model

### ISSUE THREAD

**Issue by hongshuh** [hspark1212/MOFTransformer#138]
Hi, I wonder have you tried more advanced GNN models instead of CGCNN, for example ALIGNN and coGN

**Comment by hspark1212** [comment]
Hi, @hongshuh,
Thank you for your comment. While we do have plans to explore other graph neural networks in the near future, such as MEGNet and ALIGNN, we have not yet experimented with them. We believe that these alternatives can bring further improvements, particularly in predicting properties related to local features like bandgap.
