### ISSUE TITLE
Trouble trying to parallelize MOF Transformer on multiple Nodes, Clarification

### ISSUE THREAD

**Issue by kaljamal** [hspark1212/MOFTransformer#143]
Hi, I am having some issues with training the model using multiple cpu nodes to accelerate the process. I am following the documentation as I am new to MOFTransformer and am working on training step.  I tried specifying num_nodes, num_workers and acceleration within the input. Below is my input and output (which failed after displaying some warnings), please let me know the steps and specifications involved in running training utilizing multiple cpu nodes to accelerate the process, thank you so much.
[Input.pdf](https://github.com/hspark1212/MOFTransformer/files/12297099/Input.pdf)
[Output.pdf](https://github.com/hspark1212/MOFTransformer/files/12297102/Output.pdf)

Also, I wanted to ask the function of MOFTransformer, I am new to using and am hoping to utilize as part of my research in investigating properties such as CH4 uptake and band gap within a MOF that I am working with. Is MOFTransformer able to predict these properties within singular MOFs using their respective cif file, or is the model more aptly suited to processing large datasets of MOFs? Sorry for the clarification I am new to using the model, and greatly appreciate your full explanation. Thanks so much for your time and understanding!

**Comment by Yeonghun1675** [comment]
Hi @kaljamal,

First of all, thank you for your interest in our research. We're glad to hear that our model can help you with your research.

1) In our code, num_nodes and num_workers are using the built-in of `pytorch_lightning`, a python library. Could you please check if the same problem occurs when num_nodes is 1? In our lab, we don't have a multi node system for GPU cluster, so we haven't tried to test on a multi cpu node system.  If the num_nodes issue is correct, we would appreciate it if you could use 1 core for now while we check the code.

2) If I understand correctly, you are referring to the number of data when predicting the properties of a MOF? When using a trained model to "predict" a structure of MOF, it can be applied to a single MOF. For band gap, we have uploaded a band gap fine-tuned model model trained on the QMOF dataset. (https://figshare.com/articles/dataset/MOFTransformer/21155506). You can use the model `finetuned_bandgap.ckpt` to get the band gap of your desired structure.

3) To predict the value of the model, you can use the `predict` function of moftransformer. First, prepare the data through `prepare_data`. (In prepare_data, put the cifs you want to predict in root_cifs, and set test_fraction to 1 and train_fraction to 0. Please check https://hspark1212.github.io/MOFTransformer/getting_started/prepare_data.html for more information). Then, in the predict function, make argument `split` as "test" and proceed with the prediction. Set mean and std to 2.086 and 1.131, respectively.

4) We do not provide a model for CH4 uptake.  You will need a large enough dataset to train it. As far as I know, coremof's CH4 uptake dataset is shared on the Internet. Please use it to train the model and apply it to your CIF file.
