### ISSUE TITLE
Error when reproducing the model

### ISSUE THREAD

**Issue by chenyuaner** [hspark1212/MOFTransformer#148]
Hello, i am new to learing machine learning.I want to reproducing this model. I followed the steps in the README file step by step and when I got to the step that 2.Fine-tune the pretrained MOFTransformer I got an error that FileNotFoundError: /mnt/d/mof/MOFTransformer-master/moftransformer/examples/dataset/train_example.json doesn't exist. Check 'root_dataset' in config. Is this JSON file missing from the source code on Github? How can I solve this problem?

**Comment by Yeonghun1675** [comment]
Hi @chenyuaner,

To use our model, you need to follow the prepare_data course (https://hspark1212.github.io/MOFTransformer/getting_started/prepare_data.html) and then proceed with the training.

Additionally, we noticed that the prepare_data course is missing from our readme file. We'll fix it and upload it.
