### ISSUE TITLE
Benchmark Data Request

### ISSUE THREAD

**Issue by tyvanzou** [hspark1212/MOFTransformer#153]
# Benchmark Data Request

## Intro

The result in "[PMTransformer](https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/644a0651df78ec50157390c9/original/pm-transformer-universal-transfer-learning-and-cross-material-few-shot-learning-in-porous-materials.pdf)" of Table 2 has shown different properties of porous material. Most of benchmark data including COF, PPN and MOF data are available according to the reference in the paper **except for Zeolite** data, which come from the paper [ZeoGAN](https://www.science.org/doi/10.1126/sciadv.aax9324). It seems that the author didn't provide the full data.

## Request

Is it possible to share the benchmark data of Zeolite? The structure files and property file are needed to reproduce the result in the paper.

## Other

I am a little unsure that for other benchmark, including MOF, COF and PPN, is the data provided by these references enough to reproduce the result in "PMTransformer"? Is there additional data calculated?

Thanks!

**Comment by Yeonghun1675** [comment]
Hi @tyvanzou,

We have uploaded the benchmark data you requested to figshare (https://figshare.com/articles/dataset/Benchmark_data/24884001) . Each tar file contains the cif file, graph-data, and grid-data of train/test/val. Each property is written in json format, and you can set the property downstream.

**Comment by tyvanzou** [comment]
> Hi @tyvanzou,
> 
> We have uploaded the benchmark data you requested to figshare (https://figshare.com/articles/dataset/Benchmark_data/24884001) . Each tar file contains the cif file, graph-data, and grid-data of train/test/val. Each property is written in json format, and you can set the property downstream.

Thanks for your kind sharing!
