### ISSUE TITLE
Detail of the ablation study of MOFTransformer supplementary information

### ISSUE THREAD

**Issue by tyvanzou** [hspark1212/MOFTransformer#155]
I've noticed the ablation study of pertaining data size in the SI of MOFTransformer, as shown in Supplementary Figure S7. The figure indicates the performance of H2 uptake and diffusivity and bandgap under pertaining data size of 10k, 50k, 100k, 500k, 1m. Could you please provide the detail MAE of these figure? I need it to quote your paper. Thanks!

**Comment by hspark1212** [comment]
Hi @tyvanzou,

I've attached an excel file including the finetuning results for H2 uptake, diffusivity and bandgap with the number of 20k finetuning data.
[moftransformer_pretraining_dataset.xlsx](https://github.com/hspark1212/MOFTransformer/files/14609458/moftransformer_pretraining_dataset.xlsx)

Best regards,
Hyunsoo

**Comment by tyvanzou** [comment]
Thanks very much!

**Comment by tyvanzou** [comment]
Could you please provide the whole data? I need to draw a similar graph. Because I need to compare my result, the results of H2 uptake (100bar), corresponding to the original paper are needed. Thanks!

**Comment by hspark1212** [comment]
Does the whole data mean the MAE values of H2 uptake across different fine-tuning dataset size from 5k to 20k ?
