### ISSUE TITLE
About pormake Build COF

### ISSUE THREAD

**Issue by Yong-Q** [hspark1212/MOFTransformer#156]
Your work is very meaningful and I am very interested. I would like to know where in the code the pormake is used to build structures like COF. Can you provide that ?

**Comment by Yeonghun1675** [comment]
Hi @Yong-Q ,
Thank you for your interest in our MOFTransformer and PMTransformer. I will organize and upload the code to build the structure with pormake as you mentioned, and I will reply as soon as I upload it.

**Comment by Yeonghun1675** [comment]
Hi @Yong-Q,

We upload the code that generates structures using pormake (https://github.com/Yeonghun1675/bulk_pormake_generation.git)
If you have further questions, please reply or make new issues in github.

Thanks.
