### ISSUE TITLE
Installation problem: cannot import name 'LRScheduler' from 'torch.optim.lr_scheduler' 

### ISSUE THREAD

**Issue by hrxia** [hspark1212/MOFTransformer#157]
When I install moftransformer according to the tutorial: https://hspark1212.github.io/MOFTransformer/installation.html, it is failed.

RuntimeError: Failed to import transformers.optimization because of the following error (look up to see its traceback):
cannot import name 'LRScheduler' from 'torch.optim.lr_scheduler' (./.conda/envs/mm/lib/python3.8/site-packages/torch/optim/lr_scheduler.py)

Even I created a new venv with python3.8 for this project, I still came across such problem:
DEPRECATION: pytorch-lightning 1.7.0 has a non-standard dependency specifier torch>=1.9.*. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pytorch-lightning or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

How should I address this issue? Thanks

**Comment by Yeonghun1675** [comment]
Hi @hrxia,
Thank you for your interest in our MOFTransformer and PMTransformer. Our MOFTransformer is using pytorch lightning version 1.7 for reproducibility and code stability. This may cause issues with torch 1.9 or higher. Please check if your torch is version 1;9 or higher, and if so, uninstall torch and reinstall 1.8 or lower. (https://pytorch.org/get-started/previous-versions/)

**Comment by hrxia** [comment]
Thanks @Yeonghun1675  The issue still existed. And pytorch 1.7.0 was installed:

$ pip show pytorch-lightning
Name: pytorch-lightning
Version: 1.7.0
Summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers                                                                        . Scale your models. Write less boilerplate.
Home-page: https://github.com/Lightning-AI/lightning
Author: Lightning AI et al.
Author-email: pytorch@lightning.ai
License: Apache-2.0

**Comment by Yeonghun1675** [comment]
Hi @hrxia ,
We've checked and found that the problem is a version update of the transformer library. We've released a new version (2.1.5) that fixes the requirements, so please reinstall it.

**Comment by hrxia** [comment]
Many thanks! @Yeonghun1675  It works now.
