### ISSUE TITLE
The number of training data sets in the fine-tuning process is not the same as the data set

### ISSUE THREAD

**Issue by chenyuaner** [hspark1212/MOFTransformer#164]
Hello author, i downloaded the downstream_release data set provided in the reference for fine-tuning.There are about 20000 samples in the fine-tuning data set.Why does the progress bar during fine-tuning show that i only used more than 2000 samples per epoch in the process of fine-tuning.

**Comment by Yeonghun1675** [comment]
Hi @chenyuaner,

The number shown in the progress bar is the number of batches: number of batches * batch size will give you the total sample size. (If you use "per_gpu_batchsize", than you have to multiply it instead of batchsize). 
If you have a different number of sample size, than please reply!
