### ISSUE TITLE
`poptorch_cpp_error` when trying to fine-tune moftransformer on IPU

### ISSUE THREAD

**Issue by dubeyakshat07** [hspark1212/MOFTransformer#89]
## When trying to execute `moftrasnformer.run() with accelerator = "ipu"`

Global seed set to 0
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: True, using: 1 IPUs
HPU available: False, using: 0 HPUs
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
Loading `train_dataloader` to estimate number of stepping batches.

   | Name                  | Type                | Params
---------------------------------------------------------------
0  | graph_embeddings      | GraphEmbeddings     | 132 K 
1  | token_type_embeddings | Embedding           | 1.5 K 
2  | transformer           | VisionTransformer3D | 85.3 M
3  | cls_embeddings        | Linear              | 1.5 K 
4  | volume_embeddings     | Linear              | 1.5 K 
5  | pooler                | Pooler              | 590 K 
6  | regression_head       | RegressionHead      | 769   
7  | train_regression_loss | Scalar              | 0     
8  | train_regression_mae  | Scalar              | 0     
9  | val_regression_loss   | Scalar              | 0     
10 | val_regression_mae    | Scalar              | 0     
---------------------------------------------------------------
86.0 M    Trainable params
0         Non-trainable params
86.0 M    Total params
172.099   Total estimated model params size (MB)
load model : /usr/local/lib/python3.8/dist-packages/moftransformer/database/pretrained_model.ckpt
num_device 1
read new/train_henry_coeff_H2O.json...
read new/val_henry_coeff_H2O.json...
max_epochs: 10 | max_steps: 4170 | warmup_steps : 208 | weight_decay : 0.01 | decay_power : 1
Error creating widget: could not find model
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/call.py in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     37         else:
---> 38             return trainer_fn(*args, **kwargs)
     39 

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py in _fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    649         )
--> 650         self._run(model, ckpt_path=self.ckpt_path)
    651 

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py in _run(self, model, ckpt_path)
   1102 
-> 1103         results = self._run_stage()
   1104 

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py in _run_stage(self)
   1181             return self._run_predict()
-> 1182         self._run_train()
   1183 

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py in _run_train(self)
   1194         with isolate_rng():
-> 1195             self._run_sanity_check()
   1196 

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py in _run_sanity_check(self)
   1266             with torch.no_grad():
-> 1267                 val_loop.run()
   1268 

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py in run(self, *args, **kwargs)
    198                 self.on_advance_start(*args, **kwargs)
--> 199                 self.advance(*args, **kwargs)
    200                 self.on_advance_end()

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py in advance(self, *args, **kwargs)
    151             kwargs["dataloader_idx"] = dataloader_idx
--> 152         dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
    153 

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py in run(self, *args, **kwargs)
    198                 self.on_advance_start(*args, **kwargs)
--> 199                 self.advance(*args, **kwargs)
    200                 self.on_advance_end()

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py in advance(self, data_fetcher, dl_max_batches, kwargs)
    136         # lightning module methods
--> 137         output = self._evaluation_step(**kwargs)
    138         output = self._evaluation_step_end(output)

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py in _evaluation_step(self, **kwargs)
    233         hook_name = "test_step" if self.trainer.testing else "validation_step"
--> 234         output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
    235 

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py in _call_strategy_hook(self, hook_name, *args, **kwargs)
   1484         with self.profiler.profile(f"[Strategy]{self.strategy.__class__.__name__}.{hook_name}"):
-> 1485             output = fn(*args, **kwargs)
   1486 

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/ipu.py in validation_step(self, *args, **kwargs)
    287         with self.precision_plugin.val_step_context():
--> 288             return self._step(RunningStage.VALIDATING, *args, **kwargs)
    289 

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/ipu.py in _step(self, stage, *args, **kwargs)
    279         with pl.core.module._jit_is_scripting():
--> 280             return poptorch_model(*args, **kwargs)
    281 

/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py in __call__(self, *args, **kwargs)
   1150         if not self.isCompiled():
-> 1151             self._compile(in_tensors)
   1152 

/usr/local/lib/python3.8/dist-packages/poptorch/_impl.py in wrapper(self, *args, **kwargs)
    357             with self._profiling.tracepoint(label):  # pylint: disable=protected-access
--> 358                 return func(self, *args, **kwargs)
    359 

/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py in _compile(self, in_tensors)
    910         if not self.isCompiled():
--> 911             self._executable = self._compileWithDispatch(in_tensors_trace_view)
    912 

/usr/local/lib/python3.8/dist-packages/poptorch/_impl.py in wrapper(*args, **kwargs)
    163         with OnExit():
--> 164             return func(*args, **kwargs)
    165 

/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py in _compileWithDispatch(self, in_tensors, executable_filename)
    786 
--> 787                 result = self._model(*args, **kwargs)
    788                 if result is not None:

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1189                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1190             return forward_call(*input, **kwargs)
   1191         # Do not call functions when jit is used

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/overrides/base.py in forward(self, *inputs, **kwargs)
    109             if trainer.sanity_checking or trainer.validating:
--> 110                 return self._forward_module.validation_step(*inputs, **kwargs)
    111             if trainer.predicting:

/usr/local/lib/python3.8/dist-packages/moftransformer/modules/module.py in validation_step(self, batch, batch_idx)
    266         module_utils.set_task(self)
--> 267         output = self(batch)
    268 

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1207 
-> 1208         result = forward_call(*input, **kwargs)
   1209         if _global_forward_hooks or self._forward_hooks:

/usr/local/lib/python3.8/dist-packages/moftransformer/modules/module.py in forward(self, batch)
    248             normalizer = Normalizer(self.mean, self.std)
--> 249             ret.update(objectives.compute_regression(self, batch, normalizer))
    250 

/usr/local/lib/python3.8/dist-packages/moftransformer/modules/objectives.py in compute_regression(pl_module, batch, normalizer)
     18 def compute_regression(pl_module, batch, normalizer):
---> 19     infer = pl_module.infer(batch, mask_grid=False)
     20 

/usr/local/lib/python3.8/dist-packages/moftransformer/modules/module.py in infer(self, batch, mask_grid)
    138          mo_labels,  # if moc: [B, max_graph_len], else: None
--> 139          ) = self.graph_embeddings(
    140             atom_num=atom_num,

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1207 
-> 1208         result = forward_call(*input, **kwargs)
   1209         if _global_forward_hooks or self._forward_hooks:

/usr/local/lib/python3.8/dist-packages/moftransformer/modules/cgcnn.py in forward(self, atom_num, nbr_idx, nbr_fea, crystal_atom_idx, uni_idx, uni_count, moc)
    113 
--> 114         new_atom_fea, mask, mo_label = self.reconstruct_batch(atom_fea, crystal_atom_idx, uni_idx, uni_count, moc)
    115         # [B, max_graph_len, hid_dim], [B, max_graph_len]

/usr/local/lib/python3.8/dist-packages/moftransformer/modules/cgcnn.py in reconstruct_batch(self, atom_fea, crystal_atom_idx, uni_idx, uni_count, moc)
    132             # set uni_idx with (descending count or random) and cut max_graph_len
--> 133             idx_ = torch.LongTensor([random.choice(u) for u in uni_idx[bi]])[:self.max_graph_len]
    134             rand_idx = idx_[torch.randperm(len(idx_))]

Error: In poptorch/source/dispatch_tracer/RegisterAtenOverloads.cpp:528: 'poptorch_cpp_error': aten::item is only supported in eager mode, but was intercepted in a static graph. This means an IPU to CPU copy was triggered before the end of the graph, for example by calling tensor.item(). Please ensure that any such copies are removed.

During handling of the above exception, another exception occurred:

Error                                     Traceback (most recent call last)
<ipython-input-3-1c33c9fd3e47> in <module>
     10 batch_size = 8
     11 
---> 12 moftransformer.run(root_dataset, downstream, log_dir=log_dir, 
     13                    max_epochs=max_epochs, batch_size=batch_size,accelerator="ipu")

/usr/local/lib/python3.8/dist-packages/moftransformer/run.py in run(root_dataset, downstream, log_dir, test_only, **kwargs)
    203     config['test_only'] = test_only
    204 
--> 205     main(config)
    206 
    207 

/usr/local/lib/python3.8/dist-packages/sacred/config/captured_function.py in captured_function(wrapped, instance, args, kwargs)
     40     # =================== run actual function =================================
     41     with ConfigError.track(wrapped.config, wrapped.prefix):
---> 42         result = wrapped(*args, **kwargs)
     43     # =========================================================================
     44     if wrapped.logger is not None:

/usr/local/lib/python3.8/dist-packages/moftransformer/run.py in main(_config)
    273 
    274     if not _config["test_only"]:
--> 275         trainer.fit(model, datamodule=dm)
    276         trainer.test(model, datamodule=dm)
    277     else:

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    606             raise TypeError(f"`Trainer.fit()` requires a `LightningModule`, got: {model.__class__.__qualname__}")
    607         self.strategy._lightning_module = model
--> 608         call._call_and_handle_interrupt(
    609             self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    610         )

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/call.py in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     61         for logger in trainer.loggers:
     62             logger.finalize("failed")
---> 63         trainer._teardown()
     64         # teardown might access the stage so we reset it after
     65         trainer.state.stage = None

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py in _teardown(self)
   1164         """This is the Trainer's internal teardown, unrelated to the `teardown` hooks in LightningModule and
   1165         Callback; those are handled by :meth:`_call_teardown_hook`."""
-> 1166         self.strategy.teardown()
   1167         loop = self._active_loop
   1168         # loop should never be `None` here but it can because we don't know the trainer stage with `ddp_spawn`

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/ipu.py in teardown(self)
    309             model.destroy()
    310 
--> 311         super().teardown()
    312 
    313     def _compiled(self, model: Any) -> bool:

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/parallel.py in teardown(self)
    123         assert self.cluster_environment is not None
    124         self.cluster_environment.teardown()
--> 125         super().teardown()

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/strategy.py in teardown(self)
    494         if self.lightning_module is not None:
    495             log.detail(f"{self.__class__.__name__}: moving model to CPU")
--> 496             self.lightning_module.cpu()
    497         self.precision_plugin.teardown()
    498         assert self.accelerator is not None

/usr/local/lib/python3.8/dist-packages/lightning_fabric/utilities/device_dtype_mixin.py in cpu(self)
     76         """See :meth:`torch.nn.Module.cpu`."""
     77         self.__update_properties(device=torch.device("cpu"))
---> 78         return super().cpu()
     79 
     80     def type(self, dst_type: Union[str, torch.dtype]) -> Self:  # type: ignore[valid-type]

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py in cpu(self)
    794             Module: self
    795         """
--> 796         return self._apply(lambda t: t.cpu())
    797 
    798     def type(self: T, dst_type: Union[dtype, str]) -> T:

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py in _apply(self, fn)
    637     def _apply(self, fn):
    638         for module in self.children():
--> 639             module._apply(fn)
    640 
    641         def compute_should_use_set_data(tensor, tensor_applied):

/usr/local/lib/python3.8/dist-packages/torchmetrics/metric.py in _apply(self, fn)
    645         # make sure to update the device attribute
    646         # if the dummy tensor moves device by fn function we should also update the attribute
--> 647         self._device = fn(torch.zeros(1, device=self.device)).device
    648 
    649         # Additional apply to forward cache and computed attributes (may be nested)

Error: In poptorch/source/dispatch_tracer/RegisterAtenOverloads.cpp:101: 'poptorch_cpp_error': There is no active dispatch

**Comment by hspark1212** [comment]
Hi @dubeyakshat07, this error might be related to the use of pytorch-lightning with IPU. However, it might not be possible for us to fully test the MOFTransformer with IPU as our server does not currently have an IPU card available. Can you try to run it with GPU instead of IPU?

**Comment by dubeyakshat07** [comment]
@hspark1212 Thanks for replying. Actually, the MOFTtransformer is working fine with GPU and even distributed training goes great using multiple GPUs but the main problem arises when I try to use TPU or IPU. I tried to use Paperspace's Graphcore IPU instance for the fine-tuning.

**Comment by hspark1212** [comment]
Unfortunately, we have tested the MOFTransformer only with CPU and GPU. So, it may be helpful for you take a closer look at Pytorch Lightning to fix the bug with IPU and TPU. Thanks !

**Comment by dubeyakshat07** [comment]
Thanks!
