### ISSUE TITLE
AssertionError using `PatchVisualizer`

### ISSUE THREAD

**Issue by FMcil** [hspark1212/MOFTransformer#96]
Hi! I love the paper and the installation and fine-tuning was very easy to do!

I have problems when trying to use `PatchVisualizer`. 

```
model_path = '/data/ffm2000/prisma/isotherm_prediction/moftransformer/logs/pretrained_mof_seed0_from_pretrained_model/version_0/checkpoints/last.ckpt'
downstream = 'uptake1barCO2'
data_path = "/data/ffm2000/prisma/isotherm_prediction/moftransformer/."
cifname = 'RSM0281'

cif_root = '/data/ffm2000/prisma/isotherm_prediction/moftransformer/test/.'

vis = PatchVisualizer.from_cifname(cifname, model_path, data_path,downstream=downstream,cif_root=cif_root)
vis.draw_graph()
```

I receive the following error:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[9], line 8
      4 cifname = 'RSM0281'
      6 cif_root = '/data/ffm2000/prisma/isotherm_prediction/moftransformer/test/.'
----> 8 vis = PatchVisualizer.from_cifname(cifname, model_path, data_path,downstream=downstream,cif_root=cif_root)
      9 # vis = PatchVisualizer.from_index(0, model_path, data_path)
     10 vis.draw_graph()

File ~/miniconda3/envs/pytorch-light-mof/lib/python3.8/site-packages/moftransformer/visualize/visualizer.py:136, in PatchVisualizer.from_cifname(cls, cifname, model_path, data_root, downstream, cif_root, **kwargs)
    112 @classmethod
    113 def from_cifname(cls, cifname, model_path, data_root, downstream="", cif_root=None, **kwargs):
    114     """
    115     Create PatchVisualizer from cif name. cif must be in test.json or test_{downstream}.json.
    116 
   (...)
    134     :return: PatchVisualizer class for index
    135     """
--> 136     model, data_iter = get_model_and_datamodule(model_path, data_root, downstream)
    137     batch = get_batch_from_cif_id(data_iter, cifname)
    138     if cif_root is None:

File ~/miniconda3/envs/pytorch-light-mof/lib/python3.8/site-packages/moftransformer/visualize/utils.py:38, in get_model_and_datamodule(model_path, data_root, downstream)
     35 model.to('cpu')
     37 dm = Datamodule(_config)
...
---> 41 assert os.path.isfile(path_file), f"{path_file} doesn't exist in {data_dir}"
     43 dict_target = json.load(open(path_file, "r"))
     44 self.cif_ids, self.targets = zip(*dict_target.items())

AssertionError: /home/ffm2000/miniconda3/envs/pytorch-light-mof/lib/python3.8/site-packages/moftransformer/examples/dataset/test_uptake1barCO2.json doesn't exist in /home/ffm2000/miniconda3/envs/pytorch-light-mof/lib/python3.8/site-packages/moftransformer/examples/dataset
```

I assume the error is due to `*/moftransformer/examples/*` but I was not able to fix the fault myself.

Happy to provide more information if needed.

**Comment by Yeonghun1675** [comment]
Thank you for your interest in our MOFTransformer.
We apologize for not being able to raise errors intuitively. The current issue is caused by the non-existence of [downstrem].json in the data_path. 
Please make sure that test_uptake1barCO2.json exists in that data_path (/home/ffm2000/miniconda3/envs/pytorch-light-mof/lib/python3.8/site-packages/moftransformer/examples/dataset/). If the data_path is not the path you want, please specify the data_path as the path where the data is located.

If you have any additional issues, feel free to leave a comment.

**Comment by FMcil** [comment]
Hi @Yeonghun1675, thanks for your answer.

Unfortunately I don't think the issue has been addressed.

I have specified `data_path` as an entirely different path to `/home/ffm2000/miniconda3/envs/pytorch-light-mof/lib/python3.8/site-packages/moftransformer/examples/dataset/` (which is a path to my miniconda installation, I'm not sure why it is being pointed to this). Additionally, I'm not sure why `*/examples/` is being pointed to, which makes me think this is hard-coded somewhere.

I have tried using both relative and absolute paths but I get the same error output each time.

When I have some time I will do a fresh install.

**Comment by Yeonghun1675** [comment]
I checked the code you posted above.
I created and executed the same code and saw that in version 1.1.2 (the latest version), it is pointed to the desired path.

Could you please confirm what your version is?
 It's possible that while we were modifying the code and renaming the dataloader path, some versions didn't apply correctly.
If your version is not the latest, I would appreciate it if you could upgrade to the latest version.

If you're still experiencing issues after upgrading, please let us know.
