### ISSUE TITLE
Training local property (Like atomic charge)

### ISSUE THREAD

**Issue by iawad** [hspark1212/MOFTransformer#97]
Hi authors,
I'm unsure how to set up the "downstream" file for training local properties such as partial atomic charge.

Thanks

**Comment by hspark1212** [comment]
Hi @iawad ,

Are you interested in fine-tuning a model to predict downstream properties, such as partial atomic charge? If so, please refer to the documentation on dataset preparation at https://hspark1212.github.io/MOFTransformer/dataset.html.
